services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: flask-backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://root:Aa@123456@host.docker.internal:5432/project_fusion
      - SECRET_KEY=your_secret_key
      - FLASK_ENV=development
      - FLASK_APP=manager.py
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Volume ảo để ngăn node_modules bị ghi đè
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge