FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

# Sử dụng Gunicorn với chế độ reload
CMD ["gunicorn", "--bind", "0.0.0.0:4000", "--reload", "app:create_app()"]
# CMD ["gunicorn", "--bind", "0.0.0.0:4000", "--reload", "backend.app:create_app"]
